import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#1a1a2e',
    paddingTop: 10,
  },
  header: {
    paddingHorizontal: 20,
    paddingVertical: 15,
    backgroundColor: '#FF6B35',
    alignItems: 'center',
  },
  title: {
    fontSize: 32,
    fontWeight: 'bold',
    color: '#fff',
  },
  userBar: {
    width: '100%',
    marginTop: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  userIdentityCard: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    backgroundColor: 'rgba(26, 26, 46, 0.95)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.2)',
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  userIconWrap: {
    width: 34,
    height: 34,
    borderRadius: 17,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
  },
  userNameText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '700',
  },
  userTagText: {
    color: '#FFD8CC',
    fontSize: 11,
    marginTop: 2,
    fontWeight: '600',
  },
  logoutButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    backgroundColor: '#C53A10',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.35)',
    paddingHorizontal: 12,
    paddingVertical: 10,
    minWidth: 92,
  },
  logoutButtonPressed: {
    opacity: 0.8,
    transform: [{ scale: 0.98 }],
  },
  logoutButtonText: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '700',
    letterSpacing: 0.3,
  },
  tabsContainer: {
    flexDirection: 'row',
    backgroundColor: '#2d2d44',
    borderBottomWidth: 2,
    borderBottomColor: '#FF6B35',
    justifyContent: 'space-around',
  },
  tabContent: {
    flex: 1,
  },
  searchContainer: {
    flexDirection: 'row',
    paddingHorizontal: 15,
    paddingVertical: 12,
    gap: 8,
    backgroundColor: '#2d2d44',
  },
  input: {
    flex: 1,
    backgroundColor: '#1a1a2e',
    color: '#fff',
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#FF6B35',
    fontSize: 14,
  },
  buttonContainer: {
    paddingHorizontal: 20,
    paddingVertical: 15,
    marginBottom: 10,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  loadingText: {
    marginTop: 15,
    fontSize: 16,
    color: '#FF6B35',
    fontWeight: '600',
  },
  listContainer: {
    flex: 1,
  },
  listContent: {
    paddingHorizontal: 15,
    paddingBottom: 20,
  },
  emptyContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 30,
  },
  emptyText: {
    fontSize: 16,
    color: '#888',
    textAlign: 'center',
    fontStyle: 'italic',
  },
  card: {
    backgroundColor: '#2d2d44',
    borderRadius: 12,
    padding: 15,
    marginVertical: 10,
    borderLeftWidth: 4,
    borderLeftColor: '#FF6B35',
    elevation: 5,
  },
  cardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#FF6B35',
    paddingBottom: 10,
  },
  brawlerName: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#FF6B35',
  },
  brawlerId: {
    fontSize: 12,
    color: '#888',
    backgroundColor: 'rgba(255, 107, 53, 0.1)',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 4,
  },
  statsContainer: {
    flexDirection: 'row',
    marginVertical: 12,
    gap: 8,
  },
  statBox: {
    flex: 1,
    backgroundColor: 'rgba(255, 107, 53, 0.1)',
    padding: 8,
    borderRadius: 8,
    alignItems: 'center',
  },
  statLabel: {
    fontSize: 11,
    color: '#aaa',
    marginBottom: 4,
  },
  statValue: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#FF6B35',
  },
  abilitiesSection: {
    marginTop: 10,
  },
  sectionTitle: {
    fontSize: 12,
    fontWeight: 'bold',
    color: '#FF6B35',
    marginBottom: 6,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  abilityText: {
    fontSize: 12,
    color: '#ddd',
    marginLeft: 5,
    marginVertical: 2,
  },
  playerCardScroll: {
    flex: 1,
  },
  playerCard: {
    margin: 15,
    backgroundColor: '#2d2d44',
    borderRadius: 12,
    padding: 15,
    borderLeftWidth: 4,
    borderLeftColor: '#FF6B35',
    elevation: 5,
  },
  playerHeader: {
    borderBottomWidth: 1,
    borderBottomColor: '#FF6B35',
    paddingBottom: 12,
    marginBottom: 15,
  },
  playerName: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#FF6B35',
  },
  playerTag: {
    fontSize: 12,
    color: '#888',
    marginTop: 4,
  },
  playerStatsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginBottom: 15,
  },
  playerStatBox: {
    flex: 1,
    minWidth: '45%',
    backgroundColor: 'rgba(255, 107, 53, 0.1)',
    padding: 12,
    borderRadius: 8,
    alignItems: 'center',
  },
  playerStatLabel: {
    fontSize: 11,
    color: '#aaa',
    marginBottom: 4,
  },
  playerStatValue: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#FF6B35',
  },
  playerBrawlersSection: {
    marginTop: 15,
    borderTopWidth: 1,
    borderTopColor: '#FF6B35',
    paddingTop: 12,
  },
  playerBrawlerItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: 'rgba(255, 107, 53, 0.05)',
    padding: 10,
    borderRadius: 6,
    marginVertical: 6,
  },
  playerBrawlerName: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#ddd',
  },
  playerBrawlerStats: {
    flexDirection: 'row',
    gap: 8,
  },
  playerBrawlerTrophy: {
    fontSize: 12,
    color: '#FF6B35',
    fontWeight: 'bold',
  },
  playerBrawlerLevel: {
    fontSize: 12,
    color: '#888',
  },
  playerDetailSection: {
    marginVertical: 12,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255, 107, 53, 0.3)',
  },
  detailRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 4,
  },
  detailLabel: {
    fontSize: 12,
    color: '#aaa',
    fontWeight: '600',
  },
  detailValue: {
    fontSize: 12,
    color: '#ddd',
  },
  // Styles Versus
  versusInputContainer: {
    paddingHorizontal: 15,
    paddingVertical: 12,
    backgroundColor: '#2d2d44',
    gap: 12,
  },
  versusAutoPlayerCard: {
    backgroundColor: '#1a1a2e',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: 'rgba(255, 107, 53, 0.25)',
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  versusAutoPlayerName: {
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: '700',
    marginTop: 4,
  },
  versusAutoPlayerTag: {
    color: '#FFD8CC',
    fontSize: 11,
    marginTop: 2,
    fontWeight: '600',
  },
  versusInputGroup: {
    gap: 6,
  },
  versusInputLabel: {
    fontSize: 12,
    fontWeight: 'bold',
    color: '#FF6B35',
    paddingHorizontal: 2,
  },
  versusScroll: {
    flex: 1,
  },
  versusContainer: {
    padding: 15,
  },
  versusHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
    paddingHorizontal: 10,
  },
  versusPlayerHeader: {
    flex: 1,
    alignItems: 'center',
    backgroundColor: 'rgba(255, 107, 53, 0.1)',
    padding: 12,
    borderRadius: 8,
  },
  versusPlayerName: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#FF6B35',
  },
  versusPlayerTag: {
    fontSize: 12,
    color: '#888',
    marginTop: 4,
  },
  versusVsText: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#FF6B35',
    marginHorizontal: 15,
  },
  comparisonSection: {
    marginBottom: 20,
    backgroundColor: '#2d2d44',
    borderRadius: 12,
    padding: 15,
    borderLeftWidth: 4,
    borderLeftColor: '#FF6B35',
  },
  comparisonStat: {
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: 10,
    backgroundColor: 'rgba(255, 107, 53, 0.05)',
    borderRadius: 8,
    padding: 10,
  },
  statColumn: {
    flex: 1,
    alignItems: 'center',
    padding: 10,
    backgroundColor: 'rgba(255, 107, 53, 0.1)',
    borderRadius: 6,
  },
  comparisonValue: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#FF6B35',
  },
  comparisonLabel: {
    flex: 1,
    textAlign: 'center',
    color: '#ddd',
    fontSize: 12,
    marginHorizontal: 10,
  },
  brawlerComparisonRow: {
    flexDirection: 'row',
    gap: 15,
    marginTop: 10,
  },
  brawlerComparisonColumn: {
    flex: 1,
    backgroundColor: 'rgba(255, 107, 53, 0.05)',
    borderRadius: 8,
    padding: 10,
  },
  comparisonBrawlerItem: {
    backgroundColor: 'rgba(255, 107, 53, 0.1)',
    padding: 8,
    borderRadius: 6,
    marginVertical: 6,
  },
  comparisonBrawlerName: {
    fontSize: 12,
    fontWeight: 'bold',
    color: '#FF6B35',
  },
  comparisonBrawlerStats: {
    fontSize: 10,
    color: '#888',
    marginTop: 4,
  },
});
