import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#000000',
    paddingTop: 10,
  },
  header: {
    paddingHorizontal: 20,
    paddingVertical: 15,
    backgroundColor: '#000000',
    alignItems: 'center',
    borderBottomWidth: 4,
    borderBottomColor: '#00ff00',
  },
  title: {
    fontSize: 32,
    fontWeight: 'bold',
    color: '#00ff00',
    textShadowColor: '#00ff00',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 10,
  },
  userBar: {
    width: '100%',
    marginTop: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  userIdentityCard: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    backgroundColor: '#000000',
    borderWidth: 3,
    borderColor: '#00ff00',
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  userIconWrap: {
    width: 34,
    height: 34,
    borderRadius: 17,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
  },
  userNameText: {
    color: '#00ff00',
    fontSize: 14,
    fontWeight: '700',
  },
  userIdentityTextBlock: {
    flex: 1,
    minWidth: 0,
  },
  userTagPill: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'flex-start',
    gap: 4,
    marginTop: 4,
    backgroundColor: '#000000',
    borderWidth: 2,
    borderColor: '#00ffff',
    borderRadius: 999,
    paddingHorizontal: 8,
    paddingVertical: 3,
  },
  userTagText: {
    color: '#00ffff',
    fontSize: 11,
    fontWeight: '600',
    letterSpacing: 0.2,
  },
  logoutButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    backgroundColor: '#000000',
    borderRadius: 10,
    borderWidth: 3,
    borderColor: '#ff0080',
    paddingHorizontal: 12,
    paddingVertical: 10,
    minWidth: 92,
  },
  logoutButtonPressed: {
    opacity: 0.8,
    transform: [{ scale: 0.98 }],
  },
  logoutButtonText: {
    color: '#ff0080',
    fontSize: 12,
    fontWeight: '700',
    letterSpacing: 0.3,
  },
  tabsContainer: {
    flexDirection: 'row',
    backgroundColor: '#000000',
    borderBottomWidth: 4,
    borderBottomColor: '#00ff00',
    justifyContent: 'space-around',
  },
  tabButton: {
    flex: 1,
    paddingVertical: 12,
    paddingHorizontal: 8,
    justifyContent: 'center',
    alignItems: 'center',
    borderBottomWidth: 4,
    borderBottomColor: 'transparent',
  },
  tabButtonActive: {
    borderBottomColor: '#00ff00',
  },
  tabButtonPressed: {
    opacity: 0.7,
  },
  tabButtonText: {
    fontSize: 13,
    fontWeight: '700',
    color: '#666666',
    textAlign: 'center',
  },
  tabButtonTextActive: {
    color: '#00ff00',
  },
  tabContent: {
    flex: 1,
  },
  tabScrollView: {
    flex: 1,
  },
  tabScrollContent: {
    paddingBottom: 28,
  },
  searchContainer: {
    flexDirection: 'row',
    paddingHorizontal: 15,
    paddingVertical: 12,
    gap: 8,
    backgroundColor: '#000000',
  },
  input: {
    flex: 1,
    backgroundColor: '#000000',
    color: '#00ff00',
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 8,
    borderWidth: 3,
    borderColor: '#00ff00',
    fontSize: 14,
  },
  buttonContainer: {
    paddingHorizontal: 20,
    paddingVertical: 15,
    marginBottom: 15,
    borderRadius: 10,
    backgroundColor: 'rgba(0, 255, 0, 0.05)',
    borderWidth: 2,
    borderColor: '#00ff00',
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  loadingText: {
    marginTop: 15,
    fontSize: 16,
    color: '#00ff00',
    fontWeight: '600',
  },
  listContainer: {
    flex: 1,
  },
  listContent: {
    paddingHorizontal: 15,
    paddingBottom: 20,
    backgroundColor: '#000000',
  },
  emptyContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 30,
    backgroundColor: '#000000',
  },
  emptyText: {
    fontSize: 16,
    color: '#00ff00',
    textAlign: 'center',
    fontStyle: 'italic',
  },
  card: {
    backgroundColor: '#0a0a0a',
    borderRadius: 12,
    padding: 15,
    marginVertical: 10,
    borderLeftWidth: 5,
    borderLeftColor: '#00ff00',
    borderWidth: 2,
    borderColor: '#00ff00',
    elevation: 10,
  },
  cardImageContainer: {
    width: '100%',
    height: 200,
    backgroundColor: '#000000',
    borderRadius: 8,
    marginBottom: 12,
    justifyContent: 'center',
    alignItems: 'center',
    overflow: 'hidden',
    borderWidth: 2,
    borderColor: '#00ffff',
  },
  brawlerImage: {
    width: '100%',
    height: '100%',
  },
  cardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
    borderBottomWidth: 2,
    borderBottomColor: '#00ff00',
    paddingBottom: 10,
  },
  brawlerName: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#00ff00',
  },
  brawlerId: {
    fontSize: 12,
    color: '#00ffff',
    backgroundColor: '#000000',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 4,
    borderWidth: 1,
    borderColor: '#00ffff',
  },
  statsContainer: {
    flexDirection: 'row',
    marginVertical: 12,
    gap: 8,
  },
  statBox: {
    flex: 1,
    backgroundColor: '#000000',
    padding: 8,
    borderRadius: 8,
    alignItems: 'center',
    borderWidth: 2,
    borderColor: '#00ff00',
  },
  statLabel: {
    fontSize: 11,
    color: '#00ffff',
    marginBottom: 4,
  },
  statValue: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#00ff00',
  },
  abilitiesSection: {
    marginTop: 10,
  },
  sectionTitle: {
    fontSize: 12,
    fontWeight: 'bold',
    color: '#00ff00',
    marginBottom: 6,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  abilityText: {
    fontSize: 12,
    color: '#00ffff',
    marginLeft: 5,
    marginVertical: 2,
  },
  playerCardScroll: {
    flex: 1,
  },
  playerCard: {
    margin: 15,
    backgroundColor: '#0a0a0a',
    borderRadius: 12,
    padding: 15,
    borderLeftWidth: 4,
    borderLeftColor: '#00ff00',
    borderWidth: 2,
    borderColor: '#00ff00',
    elevation: 5,
  },
  playerHeader: {
    borderBottomWidth: 2,
    borderBottomColor: '#00ff00',
    paddingBottom: 12,
    marginBottom: 15,
  },
  playerName: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#00ff00',
  },
  playerTag: {
    fontSize: 12,
    color: '#00ffff',
    marginTop: 4,
  },
  playerStatsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginBottom: 15,
  },
  playerStatBox: {
    flex: 1,
    minWidth: '45%',
    backgroundColor: '#000000',
    padding: 12,
    borderRadius: 8,
    alignItems: 'center',
    borderWidth: 2,
    borderColor: '#00ff00',
  },
  playerStatLabel: {
    fontSize: 11,
    color: '#00ffff',
    marginBottom: 4,
  },
  playerStatValue: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#00ff00',
  },
  playerBrawlersSection: {
    marginTop: 15,
    borderTopWidth: 2,
    borderTopColor: '#00ff00',
    paddingTop: 12,
  },
  playerBrawlerItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#000000',
    padding: 10,
    borderRadius: 6,
    marginVertical: 6,
    borderWidth: 1,
    borderColor: '#00ffff',
  },
  playerBrawlerName: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#00ff00',
  },
  playerBrawlerStats: {
    flexDirection: 'row',
    gap: 8,
  },
  playerBrawlerTrophy: {
    fontSize: 12,
    color: '#00ff00',
    fontWeight: 'bold',
  },
  playerBrawlerLevel: {
    fontSize: 12,
    color: '#00ffff',
  },
  playerDetailSection: {
    marginVertical: 12,
    paddingVertical: 10,
    borderBottomWidth: 2,
    borderBottomColor: '#00ff00',
  },
  detailRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 4,
  },
  detailLabel: {
    fontSize: 12,
    color: '#00ffff',
    fontWeight: '600',
  },
  detailValue: {
    fontSize: 12,
    color: '#00ff00',
  },
  // Styles Versus
  versusInputContainer: {
    margin: 15,
    padding: 14,
    backgroundColor: '#000000',
    borderRadius: 16,
    borderWidth: 3,
    borderColor: '#00ff00',
    gap: 12,
    shadowColor: '#000000',
    shadowOpacity: 0.2,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 3 },
    elevation: 4,
  },
  versusAutoPlayerCard: {
    backgroundColor: '#0a0a0a',
    borderRadius: 12,
    borderWidth: 2,
    borderColor: '#00ff00',
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  versusAutoPlayerName: {
    color: '#00ff00',
    fontSize: 16,
    fontWeight: '800',
    marginTop: 4,
  },
  versusAutoPlayerTag: {
    color: '#00ffff',
    fontSize: 12,
    marginTop: 2,
    fontWeight: '600',
  },
  versusInputGroup: {
    gap: 6,
  },
  versusInputLabel: {
    fontSize: 12,
    fontWeight: 'bold',
    color: '#00ff00',
    paddingHorizontal: 2,
  },
  versusScroll: {
    flex: 1,
    backgroundColor: '#000000',
  },
  versusContainer: {
    paddingHorizontal: 15,
    paddingTop: 0,
    backgroundColor: '#000000',
  },
  versusHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
    gap: 10,
  },
  versusPlayerHeader: {
    flex: 1,
    alignItems: 'center',
    backgroundColor: '#0a0a0a',
    paddingVertical: 14,
    paddingHorizontal: 10,
    borderRadius: 14,
    borderWidth: 2,
    borderColor: '#00ff00',
  },
  versusPlayerName: {
    fontSize: 15,
    fontWeight: '800',
    color: '#00ff00',
  },
  versusPlayerTag: {
    fontSize: 11,
    color: '#00ffff',
    marginTop: 4,
  },
  versusVsText: {
    fontSize: 18,
    fontWeight: '900',
    color: '#ff0080',
    marginHorizontal: 4,
    paddingHorizontal: 6,
  },
  comparisonSection: {
    marginBottom: 16,
    backgroundColor: '#0a0a0a',
    borderRadius: 16,
    padding: 14,
    borderWidth: 2,
    borderColor: '#00ff00',
  },
  comparisonStat: {
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: 10,
    backgroundColor: '#000000',
    borderRadius: 12,
    padding: 10,
    borderWidth: 1,
    borderColor: '#00ffff',
  },
  statColumn: {
    flex: 1,
    alignItems: 'center',
    padding: 10,
    backgroundColor: '#000000',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#00ff00',
  },
  comparisonValue: {
    fontSize: 17,
    fontWeight: '900',
    color: '#00ff00',
  },
  comparisonLabel: {
    flex: 1,
    textAlign: 'center',
    color: '#00ffff',
    fontSize: 12,
    marginHorizontal: 10,
    fontWeight: '700',
  },
  brawlerComparisonRow: {
    flexDirection: 'column',
    gap: 12,
    marginTop: 10,
  },
  brawlerComparisonColumn: {
    flex: 1,
    backgroundColor: '#000000',
    borderRadius: 12,
    padding: 12,
    borderWidth: 2,
    borderColor: '#00ff00',
  },
  brawlerComparisonPlayerName: {
    textAlign: 'center',
    fontSize: 13,
    fontWeight: '800',
    color: '#00ff00',
    marginBottom: 8,
  },
  comparisonBrawlerItem: {
    backgroundColor: '#0a0a0a',
    padding: 8,
    borderRadius: 8,
    marginVertical: 6,
    borderWidth: 1,
    borderColor: '#00ffff',
  },
  comparisonBrawlerName: {
    fontSize: 12,
    fontWeight: '800',
    color: '#00ff00',
  },
  comparisonBrawlerStats: {
    fontSize: 10,
    color: '#00ffff',
    marginTop: 4,
  },
  quickGraphSection: {
    marginTop: 6,
  },
  quickGraphCard: {
    backgroundColor: '#0a0a0a',
    borderRadius: 16,
    padding: 14,
    borderWidth: 2,
    borderColor: '#00ff00',
    gap: 12,
  },
  quickGraphRow: {
    gap: 8,
  },
  quickGraphLabel: {
    fontSize: 12,
    fontWeight: '800',
    color: '#00ffff',
    letterSpacing: 0.2,
  },
  quickGraphBars: {
    gap: 8,
  },
  quickGraphBarWrap: {
    gap: 4,
  },
  quickGraphBar: {
    height: 10,
    borderRadius: 999,
    backgroundColor: '#000000',
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: '#00ff00',
  },
  quickGraphBarLeft: {
    borderWidth: 2,
    borderColor: '#00ff00',
  },
  quickGraphBarRight: {
    borderWidth: 2,
    borderColor: '#00ffff',
  },
  quickGraphBarFill: {
    height: '100%',
    borderRadius: 999,
    backgroundColor: '#00ff00',
  },
  quickGraphBarFillRight: {
    backgroundColor: '#00ffff',
  },
  quickGraphBarValue: {
    fontSize: 10,
    color: '#00ff00',
    fontWeight: '700',
  },
  scannerModalContainer: {
    flex: 1,
    backgroundColor: '#000000',
    paddingTop: 48,
    paddingHorizontal: 16,
    paddingBottom: 24,
  },
  scannerHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 10,
  },
  scannerTitle: {
    fontSize: 22,
    fontWeight: '800',
    color: '#00ff00',
  },
  scannerSubtitle: {
    color: '#00ffff',
    fontSize: 13,
    lineHeight: 18,
    marginBottom: 16,
  },
  scannerCameraBox: {
    flex: 1,
    borderRadius: 18,
    overflow: 'hidden',
    borderWidth: 3,
    borderColor: '#00ff00',
    backgroundColor: '#000000',
  },
  scannerCamera: {
    flex: 1,
  },
  scannerCancelButton: {
    marginTop: 16,
    backgroundColor: '#000000',
    borderRadius: 12,
    paddingVertical: 14,
    alignItems: 'center',
    borderWidth: 3,
    borderColor: '#ff0080',
  },
  scannerCancelText: {
    color: '#ff0080',
    fontSize: 15,
    fontWeight: '700',
  },
  // Boutons custom pour remplacer les Button React Native
  customButton: {
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 3,
    backgroundColor: '#000000',
    borderColor: '#00ff00',
  },
  customButtonText: {
    color: '#00ff00',
    fontSize: 14,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  customButtonSecondary: {
    borderColor: '#ff0080',
  },
  customButtonSecondaryText: {
    color: '#ff0080',
  },
  customButtonPressed: {
    backgroundColor: '#1a1a1a',
  },
  countBadge: {
    marginHorizontal: 15,
    marginVertical: 10,
    paddingHorizontal: 16,
    paddingVertical: 8,
    backgroundColor: '#0a0a0a',
    borderRadius: 8,
    borderWidth: 2,
    borderColor: '#00ff00',
    alignSelf: 'center',
  },
  countText: {
    color: '#00ff00',
    fontWeight: '700',
    fontSize: 12,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
});
